package com.kino.movies.presentation.designsystem.theme

import androidx.compose.ui.graphics.Color

val kino_light_primary = Color(0xFF006874)
val kino_light_onPrimary = Color(0xFFFFFFFF)
val kino_light_primaryContainer = Color(0xFF97F0FF)
val kino_light_onPrimaryContainer = Color(0xFF001F24)
val kino_light_secondary = Color(0xFF4A6360)
val kino_light_onSecondary = Color(0xFFFFFFFF)
val kino_light_secondaryContainer = Color(0xFFCDE7EA)
val kino_light_onSecondaryContainer = Color(0xFF06201E)
val kino_light_tertiary = Color(0xFF4A6170)
val kino_light_onTertiary = Color(0xFFFFFFFF)
val kino_light_tertiaryContainer = Color(0xFFD4E7F7)
val kino_light_onTertiaryContainer = Color(0xFF061E2D)
val kino_light_error = Color(0xFFBA1A1A)
val kino_light_errorContainer = Color(0xFFFFDAD6)
val kino_light_onError = Color(0xFFFFFFFF)
val kino_light_onErrorContainer = Color(0xFF410002)
val kino_light_background = Color(0xFFFBFCFE)
val kino_light_onBackground = Color(0xFF191C1D)
val kino_light_surface = Color(0xFFFBFCFE)
val kino_light_onSurface = Color(0xFF191C1D)
val kino_light_surfaceVariant = Color(0xFFDCE4E9)
val kino_light_onSurfaceVariant = Color(0xFF40484C)
val kino_light_outline = Color(0xFF70787D)
val kino_light_inverseOnSurface = Color(0xFFEFF1F1)
val kino_light_inverseSurface = Color(0xFF2E3132)
val kino_light_inversePrimary = Color(0xFF4FD8EB)
val kino_light_shadow = Color(0xFF000000)
val kino_light_surfaceTint = Color(0xFF006874)
val kino_light_outlineVariant = Color(0xFFC0C8CC)
val kino_light_scrim = Color(0xFF000000)


val kino_dark_primary = Color(0xFF4FD8EB)
val kino_dark_onPrimary = Color(0xFF00363D)
val kino_dark_primaryContainer = Color(0xFF004F58)
val kino_dark_onPrimaryContainer = Color(0xFF97F0FF)
val kino_dark_secondary = Color(0xFFB0CCC9)
val kino_dark_onSecondary = Color(0xFF1B3532)
val kino_dark_secondaryContainer = Color(0xFF324B48)
val kino_dark_onSecondaryContainer = Color(0xFFCDE7EA)
val kino_dark_tertiary = Color(0xFFB7C9D8)
val kino_dark_onTertiary = Color(0xFF1D3340)
val kino_dark_tertiaryContainer = Color(0xFF354A57)
val kino_dark_onTertiaryContainer = Color(0xFFD4E7F7)
val kino_dark_error = Color(0xFFFFB4AB)
val kino_dark_errorContainer = Color(0xFF93000A)
val kino_dark_onError = Color(0xFF690005)
val kino_dark_onErrorContainer = Color(0xFFFFDAD6)
val kino_dark_background = Color(0xFF191C1D)
val kino_dark_onBackground = Color(0xFFE1E3E4)
val kino_dark_surface = Color(0xFF191C1D)
val kino_dark_onSurface = Color(0xFFE1E3E4)
val kino_dark_surfaceVariant = Color(0xFF40484C)
val kino_dark_onSurfaceVariant = Color(0xFFC0C8CC)
val kino_dark_outline = Color(0xFF8A9297)
val kino_dark_inverseOnSurface = Color(0xFF191C1D)
val kino_dark_inverseSurface = Color(0xFFE1E3E4)
val kino_dark_inversePrimary = Color(0xFF006874)
val kino_dark_shadow = Color(0xFF000000)
val kino_dark_surfaceTint = Color(0xFF4FD8EB)
val kino_dark_outlineVariant = Color(0xFF40484C)
val kino_dark_scrim = Color(0xFF000000)


val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)

val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)